# Generated by Django 2.2.6 on 2020-05-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='med_class',
            field=models.CharField(choices=[('class1', 'class1'), ('class2', 'class2'), ('class3', 'class3')], default='class1', max_length=8),
        ),
    ]
