# Generated by Django 2.2.6 on 2020-05-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_medicine_med_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='med_class',
            new_name='medicine_class',
        ),
    ]
