# Generated by Django 2.2.6 on 2020-05-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200526_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription_form',
            name='blurry_vision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription_form',
            name='extreme_fatigue',
            field=models.BooleanField(default=False),
        ),
    ]
