# Generated by Django 2.2.6 on 2020-05-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200526_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription_form',
            name='blurry_vision',
        ),
        migrations.RemoveField(
            model_name='prescription_form',
            name='extreme_fatigue',
        ),
        migrations.RemoveField(
            model_name='prescription_form',
            name='increased_hunger',
        ),
        migrations.RemoveField(
            model_name='prescription_form',
            name='increased_thirst',
        ),
    ]
