# Generated by Django 2.2.6 on 2020-06-02 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200527_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_form',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 15, 42, 37, 663984)),
        ),
    ]
