# Generated by Django 2.2.6 on 2020-06-02 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200602_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_form',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
