# Generated by Django 2.2.6 on 2020-06-02 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200602_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_form',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 17, 46, 36, 53646)),
        ),
    ]
