# Generated by Django 2.2.6 on 2020-06-03 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200602_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_form',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 3, 21, 45, 23, 330925)),
        ),
    ]
